Models/Domain/User.cs
namespace Meritsios_2._0.Models.Domain
{
    public class User
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string School { get; set; }
        public string Education { get; set; }
        public string Location { get; set; }
    }
}

Models/ViewModel/AddUserViewModel.cs
namespace Meritsios_2._0.Models.ViewModel
{
    public class AddUserViewModel
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string School { get; set; }
        public string Education { get; set; }
        public string Location { get; set; }
    }
}

Models/ViewModel/EditUserViewModel.cs
namespace Meritsios_2._0.Models.ViewModel
{
    public class EditUserViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string School { get; set; }
        public string Education { get; set; }
        public string Location { get; set; }
    }
}

Pages/Feed/Dashboard.cshtml.cs
using Google.Cloud.Firestore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Meritsios_2._0.Pages.Feed
{
    public class DashboardModel : PageModel
    {

        private FirestoreDb _db;
        public List<Dictionary<string, object>> Posts { get; set; }

        public DashboardModel()
        {
            string filePath =
                "./meritsios2-firebase-adminsdk-seo92-ec9db2b4c7.json";
            Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", filePath);
            _db = FirestoreDb.Create("meritsios2");
        }

        public async Task<IActionResult> OnPostAsync()
        {
            string content = Request.Form["postContent"];
            var post = new Dictionary<string, object>
            {
                {"Content", content},
                {"createdAt", DateTime.UtcNow}
            };
            await _db.Collection("posts").AddAsync(post);

            return RedirectToPage("");
        }


        public async Task OnGetAsync()
        {
            var postRef = _db.Collection("posts");
            var query = await postRef.OrderByDescending("createdAt").GetSnapshotAsync();
            Posts = query.Documents.Select(d => d.ToDictionary()).ToList();
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Meritsios_2._0.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Meritsios_2._0.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Users/Add.cshtml.cs
using Meritsios_2._0.Data;
using Meritsios_2._0.Models.Domain;
using Meritsios_2._0.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Meritsios_2._0.Pages.Users
{


    public class AddModel : PageModel
    {
        private readonly UserDbContext dbContext;

        [BindProperty] 
        public AddUserViewModel AddUserRequest { get; set; }

        public AddModel(UserDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public void OnGet()
        {
            
        }

        public IActionResult OnPost()
        {
            var userDomainModel = new User
            {
                Name = AddUserRequest.Name,
                Email = AddUserRequest.Email,
                Phone = AddUserRequest.Phone,
                School = AddUserRequest.School,
                Education = AddUserRequest.Education,
                Location = AddUserRequest.Location
                
            };

            dbContext._Users.Add(userDomainModel);
            dbContext.SaveChanges();
            return RedirectToPage("/users/ListUsers");
        }
    }
}

Pages/Users/EditUser.cshtml.cs
using Meritsios_2._0.Data;
using Meritsios_2._0.Models.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Meritsios_2._0.Pages.Users
{
    public class EditUserModel : PageModel
    {
        private readonly UserDbContext dbContext;
        [BindProperty]
        public EditUserViewModel _EditUser { get; set; }
        public EditUserModel(UserDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public void OnGet(Guid id)
        {
            var user = dbContext._Users.Find(id);

            if (user != null)
            {
                _EditUser = new EditUserViewModel()
                {
                    Id = user.Id,
                    Name = user.Name,
                    Email = user.Email,
                    Phone = user.Phone,
                    School = user.School,
                    Education = user.Education,
                    Location = user.Location
                };
            }


        }

        public IActionResult OnPostUpdate()
        {
            var user = dbContext._Users.Find(_EditUser.Id);

            if (user != null)
            {
                user.Name = _EditUser.Name;
                user.Email = _EditUser.Email;
                user.Phone = _EditUser.Phone;
                user.School = _EditUser.School;
                user.Education = _EditUser.Education;
                user.Location = _EditUser.Location;
                
                
                dbContext.SaveChanges();
                return RedirectToPage("/users/ListUsers");
            }

            return Page();


        }

        public IActionResult OnPostDelete()
        {
            var user = dbContext._Users.Find(_EditUser.Id);

            if (user != null)
            {
                dbContext._Users.Remove(user);
                dbContext.SaveChanges();
                return RedirectToPage("/users/ListUsers");
            }

            return Page();
        }


    }
}

Pages/Users/ListUsers.cshtml.cs
using Meritsios_2._0.Data;
using Meritsios_2._0.Models.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Meritsios_2._0.Pages.Users
{
    public class ListUsersModel : PageModel
    {
        private readonly UserDbContext dbContext;

        public List<User> _users { get; set; }

        public ListUsersModel(UserDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public void OnGet()
        {
            _users = dbContext._Users.ToList();
        }
    }
}

Pages/Feed/Dashboard.cshtml
@page
@model Meritsios_2._0.Pages.Feed.DashboardModel
@{
}

<div class="container-fluid">
    <div class="row">
        <div class="col-2">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Col 1</th>
                        <th>Col 2</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Row 1</td>
                        <td>Data</td>
                    </tr>
                    <tr>
                        <td>Row 2</td>
                        <td>Data</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-8 mx-auto">
            <div class=" mt-5">
                <div class="col-sm-12">
                    <form method="post">
                        <div>
                            <textarea class="form-control"
                                      name="postContent"
                                      rows="3"
                                      placeholder="Dela med dig av din dag här! :)"></textarea>
                        </div>
                        <button class="btn btn-primary" type="submit">Post</button>
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-header">Flöde</div>
                <!--Flödet går här! foreach message in firebase storage-->
                @foreach (var post in Model.Posts)
                {
                    <div class="card-header"></div>
                    <div class="card-body">

                        <div class="row">
                            <div class="col-sm-3">
                                <img src="https://via.placeholder.com/150x150" class="rounded-circle mx-auto d-block mt-3" />
                                <h4 class="text-center mt-3">John Doe</h4>
                            </div>
                            <div class="col-sm-9">
                                <div class="card my-auto">
                                    <div class="card-body">
                                        <h5 class="card-title">John Doe delade med sig</h5>
                                        <p class="card-text">@post["Content"]</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="col-2">
            <div class="card">
                <div class="card-header">Statistik</div>
                <div class="card-body">
                    <!--Statistik kontent-->
                </div>
            </div>
        </div>

    </div>
</div>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="container">
    <div class="row pt-3 ps-3">
        <div class="col-md-6">
            <h1>Meritios,</h1>
            <p>
                Allt du behöver för att digitalisera LiA
                praktiken och företagspoolen samlat i
                ett lättanvänt verktyg
            </p>
            <button class="btn btn-secondary">Boka Demo</button>
        </div>
        <div class="col-md-6 ps-3">
            <img class="h-100 w-100" src="https://wp.meritios.com/wp-content/uploads/2022/12/Namnlost-2.png" />
        </div>
    </div>
    <div class="row">
        <div class="text-center bg-primary">
            <h1>Företagspoolen samlad i
                ett CRM</h1>
            <button class="btn btn-secondary">Läs Mer</button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <img class="h-100 w-100" src="https://wp.meritios.com/wp-content/uploads/2022/12/Namnlost-3-1536x1536.png" />
        </div>
        <div class="col-md-6 text-center">
            <h1>Digalisering av LIA-Processen</h1>
            <button class="btn btn-success">Läs Mer</button>
        </div>
    </div>





</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Meritsios_2._0</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Meritsios_2._0.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Meritsios_2._0</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Hem</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Feed/dashBoard">Flöde</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-page="/users/listusers">Alla användare</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Meritsios_2._0 - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Pages/Users/Add.cshtml
@page
@model Meritsios_2._0.Pages.Users.AddModel
@{
}

<form method="post">
    <h1>Skapa en användare</h1>
    
    <div class="mb-3">
        <label class="form-label">Namn</label>
        <input class="form-control" type="text" asp-for="AddUserRequest.Name"/>
    </div>
    
    <div class="mb-3">
        <label class="form-label">Email</label>
        <input class="form-control" type="email" asp-for="AddUserRequest.Email" />
    </div>
    
    <div class="mb-3">
        <label class="form-label">Telefonnummer</label>
        <input class="form-control" type="text" asp-for="AddUserRequest.Phone" />
    </div>

    <div class="mb-3">
        <label class="form-label">Skola</label>
        <input class="form-control" type="text" asp-for="AddUserRequest.School" />
    </div>
    
    <div class="mb-3">
        <label class="form-label">Utbildning</label>
        <input class="form-control" type="text" asp-for="AddUserRequest.Education" />
    </div>
    
    <div class="mb-3">
        <label class="form-label">Stad</label>
        <input class="form-control" type="text" asp-for="AddUserRequest.Location"/>
    </div>
    
    <div class="mb-3">
        <button class="btn btn-success" type="submit">Lägg till</button>
    </div>

</form>

Pages/Users/EditUser.cshtml
@page "{id:Guid}"
@model Meritsios_2._0.Pages.Users.EditUserModel
@{
}

<form method="post">
    <h1>Editera användare</h1>
    
    <div class="mb-3">
        <label class="form-label">Id</label>
        <input class="form-control" type="text" asp-for="_EditUser.Id" readonly/>
    </div>
    <div class="mb-3">
        <label class="form-label">Namn</label>  
        <input class="form-control" type="text" asp-for="_EditUser.Name"/>
    </div>
    <div class="mb-3">
        <label class="form-label">Telefonnummer</label>
        <input class="form-control" type="text" asp-for="_EditUser.Phone" />
    </div> 
    <div class="mb-3">
        <label class="form-label">Email</label>
        <input class="form-control" type="email" asp-for="_EditUser.Email" />
    </div>   
    <div class="mb-3">
        <label class="form-label">Skola</label>
        <input class="form-control" type="text" asp-for="_EditUser.School" />
    </div> 
    <div class="mb-3">
        <label class="form-label">Utbildning</label>
        <input class="form-control" type="text" asp-for="_EditUser.Education" />
    </div>
    <div class="mb-3">
        <label class="form-label">Stad</label>
        <input class="form-control" type="text" asp-for="_EditUser.Location" />
    </div>
    <div class="mb-3 d-flex justify-content-between">
        <button type="submit" class="btn btn-success" asp-page-handler="Update">Uppdatera</button>
        <button type="submit" class="btn btn-danger" asp-page-handler="Delete">Ta bort</button>

    </div>
</form>

Pages/Users/ListUsers.cshtml
@page
@model Meritsios_2._0.Pages.Users.ListUsersModel
@{
}

<div class="container">
    <table class="table">

        <h1 class="toast-header mb-3">Alla användare:</h1>

            @if (Model._users != null && Model._users.Any())
            {
            <thead class="table-dark">
                <tr>
                    <th>Id</th>
                    <th>Namn</th>
                    <th>Email</th>
                    <th>Stad</th>
                    <th>Ös</th>
                </tr>
            </thead>
            <tbody>
                    @foreach (var user in Model._users)
                    {
                    <tr>
                        <td>@user.Id</td>
                        <td>@user.Name</td>
                        <td>@user.Email</td>
                        <td>@user.Location</td>
                        <td>
                            <a href="/users/edituser/@user.Id" class="btn btn-secondary">Edit</a>
                        </td>
                    </tr>
                    }
            </tbody>
            }
            else
            {
            <p>Inga Användare hittades!</p>
            }
        
    </table>
    <div class="mb-3">
        <a href="/users/add" class="btn btn-secondary">Lägg till användare</a>
    </div>

</div>